# tasks file for wordpress, users
---
- name: users | create (data) directory
  file:
    path: "{{ wordpress_data_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - wordpress-users-create-data-directory

- name: users | copy file
  copy:
    src: "{{ item.users.src }}"
    dest: "'{{ wordpress_data_path }}'/'{{ item.dbname }}'.csv"
    owner: root
    group: root
    mode: 0644
  register: check_copy_users
  with_items: "{{ wordpress_installs }}"
  when: item.users.src is defined
  tags:
    - wordpress-users-copy-file

- name: users | install
  command: "wp-cli --allow-root --no-color --path='{{ item.item.path }}' user import-csv '{{ wordpress_data_path }}'/'{{ item.item.dbname }}'.csv '''{{ '--skip-update' if item.item.users.skip_update | default(true) else '' }}''' --send-email"
  register: "{{ check_installation_users }}"
  changed_when: "'Success' in check_installation_users.stdout"
  with_items: "{{ check_copy_users.results }}"
  when: check_copy_users is defined and item.changed
  tags:
    - wordpress-users-import-file
